/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as LecturerDashboardRouteImport } from './routes/lecturer.dashboard'
import { Route as AuthStudentSignupRouteImport } from './routes/auth.student-signup'
import { Route as AuthStudentLoginRouteImport } from './routes/auth.student-login'
import { Route as AuthLecturerSignupRouteImport } from './routes/auth.lecturer-signup'
import { Route as AuthLecturerLoginRouteImport } from './routes/auth.lecturer-login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerDashboardRoute = LecturerDashboardRouteImport.update({
  id: '/lecturer/dashboard',
  path: '/lecturer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStudentSignupRoute = AuthStudentSignupRouteImport.update({
  id: '/auth/student-signup',
  path: '/auth/student-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStudentLoginRoute = AuthStudentLoginRouteImport.update({
  id: '/auth/student-login',
  path: '/auth/student-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLecturerSignupRoute = AuthLecturerSignupRouteImport.update({
  id: '/auth/lecturer-signup',
  path: '/auth/lecturer-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLecturerLoginRoute = AuthLecturerLoginRouteImport.update({
  id: '/auth/lecturer-login',
  path: '/auth/lecturer-login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/lecturer-login': typeof AuthLecturerLoginRoute
  '/auth/lecturer-signup': typeof AuthLecturerSignupRoute
  '/auth/student-login': typeof AuthStudentLoginRoute
  '/auth/student-signup': typeof AuthStudentSignupRoute
  '/lecturer/dashboard': typeof LecturerDashboardRoute
  '/student/dashboard': typeof StudentDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/lecturer-login': typeof AuthLecturerLoginRoute
  '/auth/lecturer-signup': typeof AuthLecturerSignupRoute
  '/auth/student-login': typeof AuthStudentLoginRoute
  '/auth/student-signup': typeof AuthStudentSignupRoute
  '/lecturer/dashboard': typeof LecturerDashboardRoute
  '/student/dashboard': typeof StudentDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/lecturer-login': typeof AuthLecturerLoginRoute
  '/auth/lecturer-signup': typeof AuthLecturerSignupRoute
  '/auth/student-login': typeof AuthStudentLoginRoute
  '/auth/student-signup': typeof AuthStudentSignupRoute
  '/lecturer/dashboard': typeof LecturerDashboardRoute
  '/student/dashboard': typeof StudentDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/lecturer-login'
    | '/auth/lecturer-signup'
    | '/auth/student-login'
    | '/auth/student-signup'
    | '/lecturer/dashboard'
    | '/student/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/lecturer-login'
    | '/auth/lecturer-signup'
    | '/auth/student-login'
    | '/auth/student-signup'
    | '/lecturer/dashboard'
    | '/student/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth/lecturer-login'
    | '/auth/lecturer-signup'
    | '/auth/student-login'
    | '/auth/student-signup'
    | '/lecturer/dashboard'
    | '/student/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLecturerLoginRoute: typeof AuthLecturerLoginRoute
  AuthLecturerSignupRoute: typeof AuthLecturerSignupRoute
  AuthStudentLoginRoute: typeof AuthStudentLoginRoute
  AuthStudentSignupRoute: typeof AuthStudentSignupRoute
  LecturerDashboardRoute: typeof LecturerDashboardRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/dashboard': {
      id: '/lecturer/dashboard'
      path: '/lecturer/dashboard'
      fullPath: '/lecturer/dashboard'
      preLoaderRoute: typeof LecturerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/student-signup': {
      id: '/auth/student-signup'
      path: '/auth/student-signup'
      fullPath: '/auth/student-signup'
      preLoaderRoute: typeof AuthStudentSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/student-login': {
      id: '/auth/student-login'
      path: '/auth/student-login'
      fullPath: '/auth/student-login'
      preLoaderRoute: typeof AuthStudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/lecturer-signup': {
      id: '/auth/lecturer-signup'
      path: '/auth/lecturer-signup'
      fullPath: '/auth/lecturer-signup'
      preLoaderRoute: typeof AuthLecturerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/lecturer-login': {
      id: '/auth/lecturer-login'
      path: '/auth/lecturer-login'
      fullPath: '/auth/lecturer-login'
      preLoaderRoute: typeof AuthLecturerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLecturerLoginRoute: AuthLecturerLoginRoute,
  AuthLecturerSignupRoute: AuthLecturerSignupRoute,
  AuthStudentLoginRoute: AuthStudentLoginRoute,
  AuthStudentSignupRoute: AuthStudentSignupRoute,
  LecturerDashboardRoute: LecturerDashboardRoute,
  StudentDashboardRoute: StudentDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
